version: '3.4'

services:
  tse:
    image: tse
    volumes:
      - ./candidates:/app/candidates
      - .:/app
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  candidates:
    name: candidates
